#!/bin/sh
pkg upgrade \
  && pkg install python \
  && pip install rapidfuzz==1.9.1 pymtheg \
  && curl https://raw.githubusercontent.com/markjoshwel/pymtheg/main/termux-url-opener -o $HOME/bin/termux-url-opener
